from pathlib import Path

ROOT_DIRECTORY_PATH = Path(__file__).parent.absolute()
DATA_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "data"
RAW_DATA_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "data" / "raw"
PROCESSED_DATA_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "data" / "processed"
METRICS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "metrics"
MODELS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "models"
REPORTS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "reports"
FEATURES_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "features"
DASHBOARD_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "dashboard"
INTERACTIVE_REPORTS_PATH = ROOT_DIRECTORY_PATH / "interactive_reports"
IMGS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "imgs"
SCRIPTS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "scripts"
NOTEBOOKS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "notebooks"

def create_dirs(*paths):
    for path in paths:
        path.mkdir(parents=True, exist_ok=True)

create_dirs(
    DATA_DIRECTORY_PATH,
    RAW_DATA_DIRECTORY_PATH,
    PROCESSED_DATA_DIRECTORY_PATH,
    METRICS_DIRECTORY_PATH,
    MODELS_DIRECTORY_PATH,
    REPORTS_DIRECTORY_PATH,
    FEATURES_DIRECTORY_PATH,
    DASHBOARD_DIRECTORY_PATH,
    INTERACTIVE_REPORTS_PATH,
    IMGS_DIRECTORY_PATH,
    SCRIPTS_DIRECTORY_PATH,
    NOTEBOOKS_DIRECTORY_PATH
)